export const FIRESTORE_COLLECTIONS = {
  CONTADORES: "contadores",
  PEDIDOS: "pedidos",
  ESCUELAS: "escuelas",
};

export const ACTIVE_FIRESTORE_COLLECTIONS = [
  FIRESTORE_COLLECTIONS.PEDIDOS,
  FIRESTORE_COLLECTIONS.CONTADORES,
  FIRESTORE_COLLECTIONS.ESCUELAS,
];

export const FIRESTORE_DOCS = {
  ORDENES: "ordenes",
};
